version: 0.2
phases:
  build:
    commands:
      - echo "Starting AI Code Review..."
      - aws lambda invoke \
          --function-name ai-code-reviewer \
          --payload file://app.py \
          response.json
artifacts:
  files:
    - response.json
